name: singer-coder
url: http://singer-coder.github.io
description: Insert tagline here

permalink: /themes/:title/

gems: [singer-coder]

highlighter: pygments
paginate: 20

markdown: rdiscount
rdiscount:
    extensions: ['smart']

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']
